#!/bin/sh
su mobile -c uicache
echo "mobile ALL=(root) NOPASSWD:/usr/bin/zxtouchb" >> /etc/sudoers
chown -R mobile:mobile /var/mobile/Library/ZXTouch
chmod +x /var/mobile/Library/ZXTouch/coreutils/ScriptRuntime/add_datetime.sh
chown root:wheel /Library/LaunchDaemons/com.zjx.zxtouchd.plist
chmod 644 /Library/LaunchDaemons/com.zjx.zxtouchd.plist
launchctl unload /Library/LaunchDaemons/com.zjx.zxtouchd.plist 2>/dev/null
launchctl load -w /Library/LaunchDaemons/com.zjx.zxtouchd.plist
