#ifndef TASK_H
#define TASK_H

#import <Foundation/Foundation.h>

#define TASK_PERFORM_TOUCH 10
#define TASK_PROCESS_BRING_FOREGROUND 11
#define TASK_SHOW_ALERT_BOX 12
#define TASK_RUN_SHELL 13
#define TASK_TOUCH_RECORDING_START 14
#define TASK_TOUCH_RECORDING_STOP 15
#define TASK_CRAZY_TAP 16
#define TASK_RAPID_FIRE_TAP 17
#define TASK_USLEEP 18
#define TASK_PLAY_SCRIPT 19
#define TASK_PLAY_SCRIPT_FORCE_STOP 20
#define TASK_TEMPLATE_MATCH 21
#define TASK_SHOW_TOAST 22
#define TASK_COLOR_PICKER 23
#define TASK_TEXT_INPUT 24
#define TASK_GET_DEVICE_INFO 25
#define TASK_TOUCH_INDICATOR 26
#define TASK_TEXT_RECOGNIZER 27
#define TASK_COLOR_SEARCHER 28
#define TASK_SCREENSHOT 29
#define TASK_HARDWARE_KEY 30
#define TASK_APP_KILL 31
#define TASK_APP_STATE 32
#define TASK_APP_INFO 33
#define TASK_FRONTMOST_APP_ID 34
#define TASK_FRONTMOST_APP_ORIENTATION 35
#define TASK_SET_AUTO_LAUNCH 36
#define TASK_LIST_AUTO_LAUNCH 37
#define TASK_SET_TIMER 38
#define TASK_REMOVE_TIMER 39
#define TASK_KEEP_AWAKE 40
#define TASK_STOP_SCRIPT 41
#define TASK_DIALOG 42
#define TASK_CLEAR_DIALOG 43
#define TASK_ROOT_DIR 44
#define TASK_CURRENT_DIR 45
#define TASK_BOT_PATH 46


#define TASK_UPDATE_CACHE 90

#define TASK_TEST 99

void processTask(UInt8 *buff, CFWriteStreamRef writeStreamRef = NULL);
static int getTaskType(UInt8* dataArray);

#endif
